### ISSUE TITLE
page refresh issue inside chat

### ISSUE THREAD

**Issue by manceelee** [justdjango/justchat#2]
When I refresh the page, the room id disappears from url, and showing a blank chat room

![image](https://user-images.githubusercontent.com/1850890/49855068-bdca7180-fdb1-11e8-84c7-9b713df7b44a.png)

If i click individual chatroom again, a new connection established, click send message and two messages adding to chat window
![image](https://user-images.githubusercontent.com/1850890/49855286-55c85b00-fdb2-11e8-94ff-d7409a161b3f.png)

**Comment by manceelee** [comment]
similar issue when i put room id after localhost, the chatroom is not automatically connected

**Comment by jatinsharrma** [comment]
@manceelee  may you share your code , i got stuck  somewhere with my template, i messed up with JavaScript i guess. it loads perfectly but not sending data to back end.
