### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by vitug110510** [justdjango/justchat#7]
can you push the main.js and style.css in this tutorials i'm stuck about 2 days in you 2nd video of your tutorials

**Comment by vitug110510** [comment]
can you push the main.js and style.css in this tutorials i'm stuck about 2 days in you 2nd video of your tutorials

**Comment by mattfreire** [comment]
The static files have always been in the repo. You just need to reset back to the commits that have them.

https://github.com/justdjango/justchat/tree/4eb38c748f77b51ffcde8684dfea173af2e33e7b/src/static
